### ISSUE TITLE
question

### ISSUE THREAD

**Issue by youle31** [lordloki/UPBGE-EEVEE#1]
Hello, there's no issue with BF to put that online?

**Comment by lordloki** [comment]
do you refer to blender icons?

**Comment by lordloki** [comment]
I will do merges with blender 2.8 regulary. I will try to complete upbge code that left yet.

Other than this you can do all the commits that you need. You don't have to ask me even :-)

**Comment by youle31** [comment]
Alright! Thanks very much. Well I guess I'm asking myself too much questions... I'll try to fix some things which I know how to fix, and maybe push a commit from time to time. Esle, thanks very much if you want to do the merges and restore remaining upbge code :)
